### ISSUE TITLE
typos in documentation

### ISSUE THREAD

**Issue by ctrlshiftq** [adamltyson/cellfinder-documentation#2]
both short and long flags for background path have typos: 

https://github.com/adamltyson/cellfinder-documentation/blob/master/user-guide/usage/README.md

**Comment by adamltyson** [comment]
Thanks. I only just saw this (for some reason I wasn't watching my own repository. I've updated the corresponding page [here](https://docs.brainglobe.info/cellfinder/user-guide/command-line).
